// AUTO-GENERATED by ai-os-scripts/generate_route_replays.py -- Phase 3 route
// replay capture/replay, route_id=RT-gst_calculation_engine-001, capability_name=gst_calculation_engine.
// Real call target + call_args reused verbatim from Phase 1's
// generate_route_tests.py REGISTERED_FIXTURES. Do not hand-edit --
// regenerate via the script.
import { calculateGst } from "@/lib/engines/in/gst-engine"

const result = calculateGst({ taxableAmount: 10000, gstRatePercent: 18, supplierStateCode: "27", buyerStateCode: "29" })
console.log(JSON.stringify(result))
