CLASSIFICATIONS = {
  "delegation-expiry": {
    "v2_id": "V2-11", "title": "Delegation expiry enforcement audit + test",
    "classification": "GENUINELY_STILL_OPEN",
    "evidence": "`src/lib/services/delegation-service.ts` has `isDelegationActive()` (line 57) and `isDelegated()` (line 143), backed by `delegation-service.test.ts` (11 passing cases). But `grep -rn \"isDelegated(\" src` outside the service file itself returns zero hits -- no authorization checkpoint (approval-workflow-service.ts, task-service.ts, report-item-action-service.ts) actually calls it. No V2-11 entry in ACTIVE-CLAIMS.yaml/COMPLETED.yaml/MASTER-TRACKER.yaml.",
    "justification": "The shared expiry-check + test exist, but the core ask -- auditing every authorization checkpoint and wiring the check in -- was never done.",
  },
  "serverless-resource-limit": {
    "v2_id": "V2-12", "title": "Serverless resource-limit tradeoff doc + heavy-workload audit",
    "classification": "GENUINELY_STILL_OPEN",
    "evidence": "No doc found anywhere in ai-os/ for this item; `ai-os/GAP_ANALYSIS_2026-07-20_HOLD.md` explicitly still lists \"V2-12 (serverless resource-limit doc)\" under the still-held Low bucket. No `maxDuration` config anywhere in src/app, no new queue/worker infra. No git commits, no ACTIVE-CLAIMS/COMPLETED entries since.",
    "justification": "Nothing has closed this since the pre-flight block; the gap analysis doc itself still lists it open.",
  },
  "chat-context-terminology": {
    "v2_id": "V2-13", "title": "Chat context + terminology + mode-pill analytics",
    "classification": "GENUINELY_STILL_OPEN",
    "evidence": "`contextEntityId` is set/read via veri-chat-service.ts/veri-meeting-service.ts but never fetched inside `generateAiReply()` in chat-service.ts (system prompt built purely from resolvePromptTemplate + buildPurposeClause). A glossary feature exists (glossary-service.ts, GlossaryTermTooltip) but is a UI hover-tooltip, not a system-prompt hook -- no glossary reference in chat-service.ts. No mode-pill-vs-free-text analytics events found anywhere. No ACTIVE-CLAIMS/COMPLETED/MASTER-TRACKER entry for V2-13.",
    "justification": "All three sub-asks (context wiring, glossary hook, mode-pill analytics) remain unbuilt.",
  },
  "preview-deployment-spotcheck": {
    "v2_id": "V2-14", "title": "Preview deployment spot-check",
    "classification": "GENUINELY_STILL_OPEN",
    "evidence": "No verification note exists in ai-os/ for row #38/V2-14 (STAGING_ENV_2026-07-20.md covers a different task, V2-7). No ACTIVE-CLAIMS/COMPLETED entry. The objective as literally scoped (spot-check the PR that was 'most recent' on 2026-07-20) is now 6 days and ~70 PRs stale -- the repo is at PR #571 today, and `gh pr checks 571` shows Build/Vercel preview both passing, so preview deployments are empirically healthy. But the written deliverable was never produced.",
    "justification": "The specific written verification note this task asked for was never produced and nothing since produced an equivalent; redispatch should target the CURRENT most-recent open PR, not the stale 2026-07-20 one.",
  },
  "storage-rls-backup-pitr": {
    "v2_id": "V2-15", "title": "Storage RLS + backup PITR + Supabase monitoring audit",
    "classification": "GENUINELY_STILL_OPEN",
    "evidence": "`drizzle/0221_wave_b_white_label_branding.sql` (lines 15-19, 66-76) explicitly documents the org-branding bucket 'carries no storage.objects RLS policies (consistent with this repo's existing compliance-documents/voice-memos buckets...)' -- i.e. the exact two buckets named in the task still have zero RLS as of the newest migration touching this area. No PITR/RTO/RPO doc found anywhere. sentry.server.config.ts/sentry.edge.config.ts exist but only reference `process.env.SENTRY_DSN` (no-op if unset); SUPERBOSS_IMPLEMENTATION_PLAN_2026-07-19_v2.md confirms the DSN provisioning itself is explicitly out of code scope and was never confirmed active. No ACTIVE-CLAIMS/COMPLETED/MASTER-TRACKER entry for V2-15.",
    "justification": "RLS gap on storage.objects is confirmed still real by the newest migration's own comment; PITR doc and Sentry activation confirmation also never produced.",
  },
  "crm-performance-under-load": {
    "v2_id": "V2-16", "title": "CRM performance-under-load indexes + load-test harness",
    "classification": "GENUINELY_STILL_OPEN",
    "evidence": "schema.ts crmLeads/crmOpportunities define no composite indexes; drizzle/0031_wave41_crm.sql and drizzle/0219_wave_b_crm_accounts_contacts.sql only add single-column indexes -- no (org_id,status,created_at) on leads, no (org_id,stage) on opportunities in any migration. Load-test harnesses exist (scripts/veridian-full-load-test.ts, scripts/projexa-load-test.ts) but exercise the orchestra/task-dispatch layer, not CRM-table query performance.",
    "justification": "The specific composite indexes and a CRM-specific load-test harness were never built.",
  },
  "hr-performance-payroll": {
    "v2_id": "V2-17", "title": "HR performance/error-handling + payroll rate audit",
    "classification": "GENUINELY_STILL_OPEN",
    "evidence": "payroll-engine.ts takes slabs/rates as caller-supplied parameters (no hardcoded seed table to audit) -- no FY-rate seed-audit artifact exists. No hits for hr-dashboard caching in src/lib/services. No load-test script mentions payroll/recruitment/attendance/vendor-scorecard.",
    "justification": "None of the three sub-asks (rate-seed audit, HR dashboard caching, payroll/recruitment/attendance load tests) show any trace in the current tree or git history.",
  },
  "multi-office-selector": {
    "v2_id": "V2-18", "title": "Multi-office selector correctness audit",
    "classification": "UNCLEAR_NEEDS_OWNER_DECISION",
    "evidence": "PR #342 (commit 58231a5b, merged) built the office/company selector backend only. PR #365 (commit 91d49840, 'Priority 17: office/company attribution for CRM leads, employee profiles, leave requests') found and fixed the exact gap in crmLeads/employeeProfiles/leaveRequests, wiring filtering into crm-service.ts/hr-service.ts/erp-budget-service.ts, and added a `supportsCompanyScope` flag per report definition in report-engine-service.ts. Commit 2c32fcc9 closed the same gap for Quotations/Sales Orders/Purchase Orders. However src/lib/services/task-service.ts and the tasks schema have zero companyId/branchId column or filter, and no standalone audit doc (the explicit V2-18 deliverable) exists anywhere; the 'currency audit' precedent V2-18 references also could not be located.",
    "justification": "Substantial real audit-and-fix work exists across ERP/CRM/HR/Reports (PRs #342/#365, commit 2c32fcc9), but the tasks-module gap and the missing formal audit doc leave it ambiguous whether V2-18 is fully closed -- owner call needed on whether the remaining tasks-module gap + doc still warrant a dedicated task.",
  },
  "prompt-cache-real-metrics": {
    "v2_id": "V2-19", "title": "Prompt & Cache real production metrics",
    "classification": "ALREADY_DONE_ELSEWHERE",
    "evidence": "PR #423, commit 70a7c91e ('FinOps: reflect prompt-cache savings in the token usage ledger', merged) is live in the tree: src/lib/prompt-cache/metrics.ts exists, recordPromptCacheMetric() (line 21) calls logTokenUsage() (line 52); schema.ts line 8913 has cacheSavingsUsd numeric column; token-usage-service.ts line 130 has getTokenUsageSummary() returning totalCacheSavingsUsd. ACTIVE-CLAIMS.yaml lines ~4638-4657 document this exact build.",
    "justification": "Precise, verifiable match to the task's exact ask, merged in PR #423.",
  },
  "search-performance-gin": {
    "v2_id": "V2-20", "title": "Search performance EXPLAIN ANALYZE + GIN index",
    "classification": "GENUINELY_STILL_OPEN",
    "evidence": "search-service.ts (the general/Standard search) uses plain ilike() against complianceItems.title/description, tasks.title/description, clients.name -- no pg_trgm/GIN index backs these columns. The pg_trgm/gin_trgm_ops hits that do exist (drizzle/0079_wave93_mdm_duplicate_detection.sql, drizzle/0085_wave107_fm_asset_registry...) serve an unrelated feature (MDM/FM dedup), not the general search path. No EXPLAIN ANALYZE results doc exists anywhere under ai-os/.",
    "justification": "The GIN infrastructure that exists is for a different feature; the search-service path this task targets is untouched.",
  },
  "e-invoicing-gstrt-irp": {
    "v2_id": "V2-21", "title": "E-invoicing per-line GstRt fix + IRP format scaffolding",
    "classification": "GENUINELY_STILL_OPEN",
    "evidence": "src/lib/services/erp-einvoice-service.ts:77 (on origin/main) still hardcodes `GstRt: 0, // per-line GST rate isn't separately tracked`. erpSalesInvoiceItems has no per-line tax-rate column (only taxTemplateId). No countryConfig/UAE e-invoice scaffolding exists anywhere in src/. The ACTIVE-CLAIMS.yaml 'Purchase-invoice text assumed... stale' reference is an unrelated duplicate-invoice-detection gap closure, not GstRt. No commit since 2026-07-20 touches erp-einvoice-service.ts.",
    "justification": "The exact hardcoded gap the task names is still present verbatim in the current code.",
  },
  "wave1-crm-schema-service-gaps": {
    "v2_id": None, "title": "Wave 1: CRM schema + service gaps (lost reason, activities, campaigns, CRUD audit)",
    "classification": "ALREADY_DONE_ELSEWHERE",
    "evidence": "PR #507 'Wave 1: CRM schema + service gaps' (commit 40423b71), PR #508 'Wave 2: CRM API routes' (b4b1ded1), PR #509 'Wave 3: CRM pages' (016ccc0e), PR #510 'Wave 4: chat wiring' -- all MERGED into origin/main on 2026-07-21. Confirmed live: crmLostReasons (schema.ts:4970), crmActivities (4978), crmCampaigns (4996), lostReasonId column on leads/opportunities (4849).",
    "justification": "A parallel/independently-dispatched wave delivered the identical objective the same day the credit gate blocked this task's 3 retry attempts.",
  },
  "canary-zero-waste-pipeline-test": {
    "v2_id": None, "title": "CANARY zero-waste-pipeline test",
    "classification": "ALREADY_DONE_ELSEWHERE",
    "evidence": "CANARY_TEST_2026_07_20.md was never written or committed on any branch -- the worker's only trace is a failed checkpoint commit (fb1880f2, exit 1) on 2026-07-20. Since then, 500+ real commits and dozens of merged PRs have landed on main through 2026-07-26.",
    "justification": "The task's sole purpose was proving the dispatch pipeline is alive at that moment; that has since been proven true repeatedly by de facto operational evidence (every subsequent successful task/PR). Redispatching a synthetic self-test now is pure waste.",
  },
  "billstack-bharatnet-reverse-eng": {
    "v2_id": None, "title": "Billstack bharatnet reverse-engineering",
    "classification": "ALREADY_DONE_ELSEWHERE",
    "evidence": "docs/billstack-bharatnet/ is empty on main, but the full 8-file documentation set (00-navigation-map.md, SUMMARY.md, vendors.md, customers.md, supplier-bills.md, sales-invoices-and-receipts.md, payments-and-purchase-invoices-table.md, masters-items-tax-org-users.md) already exists complete on branch worker/task-20260720-060747-billstack-bharatnet-reverse-engineering (commits 5d2c61a..4866d1b, 'Mark task complete: all Billstack Bharatnet docs written and pushed', dated 2026-07-20).",
    "justification": "The deliverable was actually produced before the credit gate hit; it sits complete on an unmerged branch. This needs a PR/merge action on the existing branch, not a fresh redispatch -- redispatching would duplicate real, already-finished work.",
  },
  "cityline-ticketing-reverse-eng": {
    "v2_id": None, "title": "Cityline Ticketing 6-role reverse-engineering",
    "classification": "GENUINELY_STILL_OPEN",
    "evidence": "main has only docs/cityline-ticketing/tickets-dashboard.md (53 lines, one page). Merge commit 9c5538b narrates 'Only 1 of the 6 originally-scoped roles was exercised' via the Owner's own already-authenticated session. Worker branch worker/task-20260720-060752-cityline-ticketing-6-role-reverse-engine contains only 00-BLOCKER-login-failures.md -- all 6 role-account logins failed and were never resolved.",
    "justification": "The core 6-role, function-by-function documentation objective remains largely unmet; nothing since 2026-07-20 has closed this gap.",
  },
  "mother-router-roster-memory": {
    "v2_id": None, "title": "mother-router-and-roster-persistent-memory",
    "classification": "GENUINELY_STILL_OPEN",
    "evidence": "ai-os/SYSTEM_MEMORY_ARCHITECTURE.yaml (authored 2026-07-22, AFTER the credit-gate block) explicitly states layer_3_mother_router: status: CONFIRMED_GAP_DESIGNED_NOT_BUILT and layer_5_ai_agents_roster: status: CONFIRMED_GAP_DESIGNED_NOT_BUILT. Independent grep of schema.ts and the whole repo for mother_router_memory/ai_agent_memory returns zero matches; no migration references them.",
    "justification": "A later, independent review (2026-07-22) reconfirmed the exact same gap and notes it is deliberately deferred per the Owner's own sequencing rule -- the gap is real, current, and explicitly still open by the system's own architecture doc.",
  },
  "shared-cross-repo-prompt-pattern": {
    "v2_id": "V2-4", "title": "Shared cross-repo prompt-pattern module",
    "classification": "UNCLEAR_NEEDS_OWNER_DECISION",
    "evidence": "veridian-ui-kit commit 1f8fe45 ('Add shared cross-repo prompt-pattern module (SUPERBOSS v2 V2-4) (#5)', 2026-07-20) added a full tested module at src/prompt-patterns/ (catalog.ts, runner.ts, types.ts + tests). However both compliance-tracker/package.json and projexa/package.json still pin veridian-ui-kit at v0.2.2, which predates 1f8fe45 -- the pinned version does not include the module, and no call sites (PromptPattern/runPromptPattern) exist in either repo's src/. gap_queue.yaml's own V2-4 entry requires 'Module + 2 adoptions + tests; PRs in both repos' as done criteria.",
    "justification": "The hard design/build part is done, but the explicit done-criteria (dependency bump + adoption in both repos) is unmet -- an owner should decide whether the remaining work is a small follow-up task rather than a full rebuild.",
  },
  "executive-reporting-drilldown": {
    "v2_id": "V2-22", "title": "Executive reporting drill-down + cadence scheduled job",
    "classification": "UNCLEAR_NEEDS_OWNER_DECISION",
    "evidence": "A real cadence/delivery mechanism exists: report-schedule-service.ts (report_schedules table with a genuine cadence field, predates the 2026-07-20 freeze) + a live Vercel cron (vercel.json, '45 8 * * *') calling runDueReportSchedules(), delivering via the notifications table -- but the literal field the task names (report_definitions.cadence) doesn't exist; report_definitions has periodicity instead, with cadence living on the separate report_schedules table. No 'executive dashboard' page/component was found anywhere in src/app/(app)/** or src/components/** (only a 33-line thin dashboard/page.tsx wrapper) -- the drill-down half shows no positive evidence either way. SUPERBOSS_IMPLEMENTATION_PLAN_2026-07-19_v2.md still lists V2-22 as open on current origin/main.",
    "justification": "The cadence-delivery half looks functionally covered by pre-existing infrastructure (though not an exact field-name match); the drill-down half is unverifiable in a 10,000+ line schema without deeper investigation -- owner call needed rather than a forced verdict.",
  },
  "remove-anthropic-api-key": {
    "v2_id": "V2-23", "title": "Remove ANTHROPIC_API_KEY dead code path",
    "classification": "GENUINELY_STILL_OPEN",
    "evidence": ".github/workflows/ai-dispatch.yml:4 still lists claude-task as a trigger type; .github/workflows/claude.yml:37 still references secrets.ANTHROPIC_API_KEY; src/lib/orchestra-model-resolver.ts:200 still has case \"anthropic\": return process.env.ANTHROPIC_API_KEY; src/lib/ai-team/roster.ts:134 still comments on the dead claude-task path. ai-os/GAP_ANALYSIS_2026-07-20_HOLD.md:65 (current origin/main) still explicitly lists V2-23 as one of the ~185 genuinely-open items.",
    "justification": "All call sites for the dead path are still present verbatim; nothing since has removed them.",
  },
  "crm-contacts-list-route": {
    "v2_id": "V2-24", "title": "CRM Contacts list route + page (the one genuinely-missing Wave B piece)",
    "classification": "ALREADY_DONE_ELSEWHERE",
    "evidence": "PR #509 'Wave 3: CRM pages -- Leads, Opportunities/Kanban, Contacts, Campaigns, hub refactor' (commit 016ccc0e, merged 2026-07-21) added src/app/api/crm/contacts/route.ts (GET handler calling listContactsPaged, comment: 'Wave 3 (2026-07-21): first-ever org-wide contacts list') and src/app/(app)/crm/contacts/page.tsx. src/app/api/crm/contacts/[id]/route.ts also still exists alongside it.",
    "justification": "The exact missing HTTP/UI surface this task named was added by PR #509, one day after the credit gate blocked this task.",
  },
  "continue-autonomous-gap-queue": {
    "v2_id": "V2-25", "title": "Continue the autonomous gap_queue (system-driven, NOT a manual dispatch)",
    "classification": "ALREADY_DONE_ELSEWHERE",
    "evidence": "ai-os/gap_queue.yaml and scripts/queue-dispatcher.py exist; crontab (*/10 * * * *) confirms it still runs every 10 minutes via run-logged.sh; logs/queue-dispatcher.log shows continuous, non-erroring execution through recent runs. gap_queue.yaml shows dispatch_paused: true, pause_reason: 'Owner directive 2026-07-20: ... do NOT work on them further until explicitly released', holding 21 task_ids (including several tasks in this very triage batch).",
    "justification": "The system this task was meant to monitor is alive, functioning exactly as designed, and continuously self-logs its own health -- a fresh 'monitor' dispatch would surface nothing the log doesn't already show. The 6+ day pause itself is an unpause decision for the owner, not a gap in the monitoring task.",
  },
}
