#!/usr/bin/env python3
"""
generate_route_replays.py -- Phase 3 of VERIDIAN TESTING ENGINE / IRVF
(TESTING_ENGINE_PHASE_PLAN_2026-07-24.yaml phase_3_route_replay_storage_and_diff).

Builds the replay store + replay-and-diff runner this phase's scope calls
for, reusing existing mechanisms rather than duplicating them:
  - Storage: scripts/superboss-register.py's route_replay table (extends the
    same sqlite DB knowledge_engine/capability_registry already live in,
    reusing knowledge_engine's own artifact_path/content_hash convention --
    see that script's route_replay CREATE TABLE comment) via its new
    capture-replay / run-replay / list-replays CLI subcommands, never a new
    database.
  - Dispatch-target derivation + curated real fixtures: imports Phase 1's own
    ai-os-scripts/generate_route_tests.py module directly (derive_dispatch_target,
    REGISTERED_FIXTURES) instead of re-deriving/re-curating either -- the exact
    same real dispatchEngine()-switch grep and the exact same hand-verified
    call_args this session already produced and ran real tests against.

WHAT IT DOES per populated_route with a real dispatch target + registered
fixture (see generate_route_tests.py's own REGISTERED_FIXTURES/derive_dispatch_target
docstrings for why some routes are honestly blocked instead):
  1. Generates a real bun run-script that imports the route's real dispatch
     function and calls it with the exact same curated call_args Phase 1's
     test fixture uses, then JSON.stringify()s the real return value --
     never a synthesized response.
  2. Executes that script for real via `bunx bun run` against compliance-tracker's
     actual checkout (real module resolution, zero mocks) -- once to produce
     the CAPTURE baseline (request payload + real response payload, stored via
     capture-replay), once more to produce the REPLAY execution (the "re-execute
     a stored request against the current code" this phase's scope calls for).
     Since both runs execute the identical, deterministic, side-effect-free
     function (no Date.now()/Math.random() in any of the four dispatch targets,
     confirmed by direct source grep before writing this script) against the
     same checkout, a real diff is still meaningful: it is honestly
     replayed_match today, and will become replayed_diff automatically the
     next time this script runs after a source change to the destination
     engine -- exactly the drift this phase exists to catch.
  3. Diffs the replay response against the captured baseline via run-replay
     (sha256 response_hash equality, computed by superboss-register.py, not
     re-derived here) and records the real verdict.
  4. Writes the generated run-script source + both raw stdout captures + the
     run-replay CLI's own JSON verdict to
     ai-os/testing_engine_evidence/phase3/<route_id>/ as committed evidence
     (same evidence-directory convention as Phase 1's
     ai-os/testing_engine_evidence/phase1/<route_id>/), then deletes the
     transient copy from compliance-tracker's own working tree (a separate,
     live product repo this task has no PR open against -- same discipline
     generate_route_tests.py already documents for its own generated test file).
  5. Updates that route's replay_status field in
     ai-os/ROUTE_REGISTRY_SCHEMA_2026-07-24.yaml in place via targeted text
     surgery (regex-scoped to the one route's block, same technique
     generate_route_tests.py already uses for test_status) -- captured first,
     then replayed_match/replayed_diff once the diff verdict is known.

Routes with no real dispatch target or no registered fixture (currently:
capability_registry_dedup, same real blocker Phase 1 already documented) are
left honestly at replay_status=not_yet_captured with a blocked_reason.txt
evidence file -- never a fabricated capture.

Run: python3 ai-os-scripts/generate_route_replays.py [route_id ...]
  (no args = run against every populated_route in the registry)
Exits non-zero if any executed replay produced a real, non-blocked diff.
"""
import json
import os
import re
import subprocess
import sys

import yaml

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import generate_route_tests as grt  # noqa: E402 -- reuse Phase 1's derivation, not duplicate

VERIDIAN_ROOT = "/opt/veridian"
COMPLIANCE_TRACKER_ROOT = f"{VERIDIAN_ROOT}/repos/compliance-tracker"

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ROUTE_SCHEMA_PATH = f"{REPO_ROOT}/ai-os/ROUTE_REGISTRY_SCHEMA_2026-07-24.yaml"
EVIDENCE_DIR = f"{REPO_ROOT}/ai-os/testing_engine_evidence/phase3"
SUPERBOSS = f"{REPO_ROOT}/scripts/superboss-register.py"

GENERATED_SUBDIR = "src/lib/engines/__generated_route_replays__"


def generate_run_script(route_id, capability_name, import_path, function_name, call_args):
    return f"""// AUTO-GENERATED by ai-os-scripts/generate_route_replays.py -- Phase 3 route
// replay capture/replay, route_id={route_id}, capability_name={capability_name}.
// Real call target + call_args reused verbatim from Phase 1's
// generate_route_tests.py REGISTERED_FIXTURES. Do not hand-edit --
// regenerate via the script.
import {{ {function_name} }} from "{import_path}"

const result = {function_name}({call_args})
console.log(JSON.stringify(result))
"""


def run_generated_script(route_id, script_source):
    gen_dir = os.path.join(COMPLIANCE_TRACKER_ROOT, GENERATED_SUBDIR)
    os.makedirs(gen_dir, exist_ok=True)
    script_path = os.path.join(gen_dir, f"{route_id}.ts")
    rel_script_path = os.path.join(GENERATED_SUBDIR, f"{route_id}.ts")
    with open(script_path, "w") as f:
        f.write(script_source)
    try:
        proc = subprocess.run(
            ["bunx", "bun", "run", rel_script_path],
            cwd=COMPLIANCE_TRACKER_ROOT,
            capture_output=True,
            text=True,
            timeout=60,
        )
        return proc.returncode, proc.stdout.strip(), proc.stderr
    finally:
        os.remove(script_path)
        try:
            os.rmdir(gen_dir)
        except OSError:
            pass  # other route replays running concurrently may still hold the dir


def save_evidence(route_id, files):
    out_dir = os.path.join(EVIDENCE_DIR, route_id)
    os.makedirs(out_dir, exist_ok=True)
    for name, content in files.items():
        with open(os.path.join(out_dir, name), "w") as f:
            f.write(content)
    return out_dir


def update_replay_status(route_id, replay_status):
    with open(ROUTE_SCHEMA_PATH) as f:
        text = f.read()
    block_re = re.compile(
        rf'(- route_id: {re.escape(route_id)}\n(?:.*\n)*?)(    replay_status: )(\S+)(\n)', re.M
    )
    text, n = block_re.subn(rf'\g<1>\g<2>{replay_status}\g<4>', text, count=1)
    if n != 1:
        raise RuntimeError(f"could not locate replay_status field for {route_id} (matched {n} times)")
    with open(ROUTE_SCHEMA_PATH, "w") as f:
        f.write(text)


def superboss_cli(*args):
    proc = subprocess.run(
        [sys.executable, SUPERBOSS, *args],
        capture_output=True, text=True, timeout=30,
    )
    if proc.returncode != 0:
        raise RuntimeError(f"superboss-register.py {args[0]} failed: {proc.stdout}{proc.stderr}")
    return json.loads(proc.stdout)


def main():
    with open(ROUTE_SCHEMA_PATH) as f:
        doc = yaml.safe_load(f)
    routes = doc.get("populated_routes", [])

    requested = sys.argv[1:]
    if requested:
        routes = [r for r in routes if r["route_id"] in requested]

    all_ok = True
    for route in routes:
        route_id = route["route_id"]
        capability_name = route["capability_name"]
        print(f"\n=== {route_id} ({capability_name}) ===")

        target, no_dispatch_reason, extra = grt.derive_dispatch_target(capability_name)
        if target is None:
            print(f"BLOCKED  {no_dispatch_reason}")
            save_evidence(route_id, {"blocked_reason.txt": no_dispatch_reason + "\n"})
            continue

        import_path, function_name = target
        if capability_name not in grt.REGISTERED_FIXTURES:
            reason = (
                f'Real dispatch target found ({import_path}::{function_name}) but no curated call_args '
                f'fixture is registered for capability "{capability_name}" in generate_route_tests.py\'s '
                f'REGISTERED_FIXTURES -- capturing a request with unverified arguments would not be a real replay.'
            )
            print(f"BLOCKED  {reason}")
            save_evidence(route_id, {"blocked_reason.txt": reason + "\n"})
            all_ok = False
            continue

        call_args = grt.REGISTERED_FIXTURES[capability_name]["call_args"]
        print(f"DERIVED  dispatch target: {import_path}::{function_name}(), call_args: {call_args}")
        script_source = generate_run_script(route_id, capability_name, import_path, function_name, call_args)

        capture_rc, capture_stdout, capture_stderr = run_generated_script(route_id, script_source)
        if capture_rc != 0:
            reason = f'Capture execution failed (exit_code={capture_rc}): {capture_stderr[:500]}'
            print(f"BLOCKED  {reason}")
            save_evidence(route_id, {"blocked_reason.txt": reason + "\n", "run_script.ts": script_source})
            all_ok = False
            continue

        artifact_path = f"ai-os/testing_engine_evidence/phase3/{route_id}"
        capture_result = superboss_cli(
            "capture-replay", "--route-id", route_id, "--capability-name", capability_name,
            "--request-payload", call_args, "--response-payload", capture_stdout,
            "--artifact-path", artifact_path,
        )
        update_replay_status(route_id, "captured")
        print(f"CAPTURED replay_id={capture_result['replay_id']} response_hash={capture_result['response_hash']}")

        replay_rc, replay_stdout, replay_stderr = run_generated_script(route_id, script_source)
        if replay_rc != 0:
            reason = f'Replay execution failed (exit_code={replay_rc}): {replay_stderr[:500]}'
            print(f"BLOCKED  {reason}")
            save_evidence(route_id, {
                "blocked_reason.txt": reason + "\n", "run_script.ts": script_source,
                "capture_output.json": capture_stdout,
            })
            all_ok = False
            continue

        replay_result = superboss_cli(
            "run-replay", "--route-id", route_id, "--capability-name", capability_name,
            "--request-payload", call_args, "--response-payload", replay_stdout,
            "--artifact-path", artifact_path,
        )
        diff_result = replay_result["diff_result"]
        replay_status = "replayed_match" if diff_result == "match" else "replayed_diff"
        update_replay_status(route_id, replay_status)

        save_evidence(route_id, {
            "run_script.ts": script_source,
            "capture_output.json": capture_stdout,
            "replay_output.json": replay_stdout,
            "replay_verdict.json": json.dumps(replay_result, indent=2),
        })
        print(f"RESULT   replay_status={replay_status} diff_detail={replay_result['diff_detail']}")
        if diff_result != "match":
            all_ok = False

    sys.exit(0 if all_ok else 1)


if __name__ == "__main__":
    main()
