#!/usr/bin/env python3
"""
generate_terminology_guardrail_exemptions.py -- Phase 3 CI enforcement wiring
(task-20260724-133911-terminology-phase3-ci-enforcement-wiring, instruction
INS-20260724-133817-0a6d, ai-os/TERMINOLOGY_STANDARDIZATION_PHASE_PLAN_2026-07-24.yaml
phase_3_ci_enforcement_wiring).

Mechanically builds compliance-tracker's ai-os/registry/terminology-guardrail-exemptions.yaml
from Phase 2's real per-directory findings baseline reports
(ai-os/guardrail-findings/{src-lib-services,src-lib-toplevel,src-app-api,
src-seed-and-test-fixtures}-2026-07-24.json). Per this task's standing rule
("registry writes come from scripts not hand-authored prose"), the exemption
file's initial content is generated here, not typed by hand.

Exemption granularity: per (file, category) finding COUNT, not per exact
line/matched-text. scripts/check-terminology-guardrail.mjs (the ported CI
gate) treats an exempted file's recorded count per category as the allowed
baseline -- if a re-scan of that file finds MORE findings of a category than
recorded here, the excess is new debt and fails CI; a file not listed here at
all must have zero findings. This is deliberately a ratchet ("count may not
increase"), not an exact-instance match, because line numbers shift as
unrelated edits land in the same file -- honest limitation, stated in the
check script's own header: a PR that deletes one pre-existing finding and
introduces a different one in the same file/category, keeping the count
static, would not be caught. Matches this codebase's own convention of
naming what a guardrail does and doesn't guarantee (see
scripts/check-guardrail-presence.mjs's header for the precedent).

Run:
  python3 ai-os-scripts/generate_terminology_guardrail_exemptions.py --output <path>
"""
import argparse
import json
import os

REPO_PREFIX = "/opt/veridian/repos/compliance-tracker/"
REPO_PREFIX_ALT = "/opt/veridian/workspace/claude-cli-work/compliance-tracker/"

FINDINGS_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "ai-os", "guardrail-findings")

SOURCE_REPORTS = [
    ("src-lib-services-2026-07-24.json", "src-lib-services", "required_fix_candidate"),
    ("src-lib-toplevel-2026-07-24.json", "src-lib-toplevel", "required_fix_candidate"),
    ("src-app-api-2026-07-24.json", "src-app-api", "required_fix_candidate"),
    ("src-seed-and-test-fixtures-2026-07-24.json", "src-seed-and-test-fixtures", "exemption_candidate"),
]


def relativize(path):
    if path.startswith(REPO_PREFIX):
        return path[len(REPO_PREFIX):]
    if path.startswith(REPO_PREFIX_ALT):
        return path[len(REPO_PREFIX_ALT):]
    raise ValueError(f"finding source path not under a known compliance-tracker checkout root: {path}")


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", required=True, help="path to write terminology-guardrail-exemptions.yaml")
    args = parser.parse_args()

    # file -> category -> count
    per_file = {}
    # file -> set of sweep slugs it was scanned in (for the reason line)
    file_sweeps = {}

    total_findings_seen = 0
    for filename, slug, classification in SOURCE_REPORTS:
        report_path = os.path.join(FINDINGS_DIR, filename)
        with open(report_path) as f:
            report = json.load(f)
        for finding in report["findings"]:
            rel = relativize(finding["source"])
            total_findings_seen += 1
            per_file.setdefault(rel, {})
            per_file[rel][finding["category"]] = per_file[rel].get(finding["category"], 0) + 1
            file_sweeps.setdefault(rel, set()).add((slug, classification))

    lines = []
    lines.append("# Phase 3 CI enforcement wiring (task-20260724-133911-terminology-phase3-ci-enforcement-wiring,")
    lines.append("# instruction INS-20260724-133817-0a6d) -- the CI-enforced exemption manifest for")
    lines.append("# scripts/check-terminology-guardrail.mjs, same enforcement class as")
    lines.append("# ai-os/registry/asset-registry-coverage.yaml (a reviewable-diff ratchet, not a")
    lines.append("# runtime-unbypassable lock -- named honestly, not oversold).")
    lines.append("#")
    lines.append("# Seeded from Phase 2's real per-directory findings baseline")
    lines.append("# (ai-os/guardrail-findings/{src-lib-services,src-lib-toplevel,src-app-api,")
    lines.append("# src-seed-and-test-fixtures}-2026-07-24.json, task-20260724-115921-phase2-directory-scoped-")
    lines.append("# guardrail-rollout) -- generated by")
    lines.append("# ai-os-scripts/generate_terminology_guardrail_exemptions.py, not hand-typed.")
    lines.append("#")
    lines.append(f"# {len(per_file)} files, {total_findings_seen} pre-existing findings grandfathered at Phase 3")
    lines.append("# wiring time. Each entry's findings_by_category is the MAXIMUM allowed count for that")
    lines.append("# category in that file -- check-terminology-guardrail.mjs fails CI only when a re-scan")
    lines.append("# finds MORE than this recorded baseline (new debt), never on the pre-existing count")
    lines.append("# itself. Phase 4 (migration) is expected to shrink these counts over time as literals")
    lines.append("# are replaced with registered <Entity.Attribute> placeholders; Phase 5 retires this file")
    lines.append("# once every count reaches 0.")
    lines.append("")
    lines.append("exemptions:")

    for rel in sorted(per_file.keys()):
        categories = per_file[rel]
        sweeps = sorted(file_sweeps[rel])
        sweep_desc = ", ".join(f"{slug} ({cls})" for slug, cls in sweeps)
        total = sum(categories.values())
        reason = (
            f"Phase 2 baseline ({sweep_desc}, 2026-07-24): {total} pre-existing finding(s) "
            f"grandfathered pending Phase 4 migration."
        )
        lines.append(f"  - file: {rel}")
        lines.append(f"    reason: \"{reason}\"")
        lines.append("    findings_by_category:")
        for cat in sorted(categories.keys()):
            lines.append(f"      {cat}: {categories[cat]}")

    output_path = os.path.abspath(args.output)
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    with open(output_path, "w") as f:
        f.write("\n".join(lines) + "\n")

    print(f"Wrote {output_path}: {len(per_file)} files, {total_findings_seen} findings grandfathered.")


if __name__ == "__main__":
    main()
