#!/usr/bin/env python3
"""VERIDIAN Auditor Engine -- Phase 5, ddd domain AI Review.

Registers the 5 real judgment findings from
ai-os/DDD_SEMANTIC_REVIEW_2026-07-24.yaml into the same shared
audit_findings table Phase 1-4's deterministic pipelines already write
into -- remediation_type=ai_escalation_required (never software_fixable:
these are judgment calls a lint rule structurally cannot make, per that
document's own per-finding rationale), producer_kind=ai_review (not
oss_tool/custom_script -- distinct producer_kind, matching this plan's own
PART5 distinction between software and AI Review findings).

The finding content itself (id, severity, title, finding text) is NOT
generated by this script -- it is copied verbatim from the review
document, which is the real artifact a human/future phase should read.
This script's only job is to make those 5 real judgment calls queryable
alongside every other domain's findings, idempotently. Same structural
pattern as register_enterprise_architecture_drift_findings.py (Phase 4).

Usage:
    python3 register_ddd_semantic_findings.py [--dry-run]
"""
import argparse
import contextlib
import datetime
import fcntl
import hashlib
import json
import os
import sqlite3
import sys

DB_PATH = os.environ.get("SUPERBOSS_REGISTER_DB", "/opt/veridian/ai-os/memory/superboss-register.sqlite")
_WRITE_LOCK_PATH = DB_PATH + ".writelock"

DOMAIN = "ddd"
STANDARD_CITED = ("Eric Evans, Domain-Driven Design (2003) + Vaughn Vernon, Implementing Domain-Driven "
                   "Design (2013) -- the canonical DDD reference texts (no ISO body governs DDD)")
REVIEWER_VERSION = "claude-sonnet-5-2026-07-24"
SOURCE_DOC = "ai-os/DDD_SEMANTIC_REVIEW_2026-07-24.yaml"

# Copied verbatim from ai-os/DDD_SEMANTIC_REVIEW_2026-07-24.yaml
_FINDINGS = [
    {
        "id": "DDD-AI-001", "repo": "compliance-tracker", "severity": "low",
        "title": "The 4 flagged 'cross-context' imports are literal re-exports within one documented bounded context, not aggregate leakage",
        "finding": "All 4 files dependency-cruiser flagged are one-line re-exports of the construction "
                   "domain's real handler -- confirmed by reading all 4 files plus their 4 construction-side "
                   "counterparts. schema.ts explicitly documents the intent as a deliberate 2026-07-08 "
                   "decision to expose construction modules via /api/v1 rather than duplicate them. The "
                   "dependency-cruiser rule matches on directory naming, not actual aggregate ownership.",
        "artifact_path": "src/app/api/v1/projexa/ai/{diff-drawings,estimate-progress,progress-summary,risk-detection}/route.ts",
    },
    {
        "id": "DDD-AI-002", "repo": "compliance-tracker", "severity": "medium",
        "title": "The 4 flagged routes break the /v1/projexa/* namespace's own established auth contract",
        "finding": "Every other route under v1/projexa/* (~40 checked) uses requireAuthOrApiKey, matching "
                   "projexa's veridian-client.ts documented Bearer-API-key contract, but these 4 AI routes "
                   "are session-only (requireAuth) -- structurally inside the public surface but uncallable "
                   "by PROJEXA's own server client. Confirmed latent (projexa does not currently call them).",
        "artifact_path": "src/app/api/v1/projexa/ai/diff-drawings/route.ts",
    },
    {
        "id": "DDD-AI-003", "repo": "compliance-tracker", "severity": "info",
        "title": "The Organization aggregate has two incompatible identities across repos, correctly bridged but with spelling drift",
        "finding": "compliance-tracker's aggregate root is 'organisations' (British), projexa's is "
                   "'organizations' (American) with a different id type -- bridged correctly via an "
                   "explicit anti-corruption table (veridianCredentials, PROJEXA-IDENTITY-BRIDGE-01) but "
                   "the vocabulary spelling itself drifts across the two repos' domain language.",
        "artifact_path": "src/lib/db/schema.ts (lines 28-29)",
    },
    {
        "id": "DDD-AI-004", "repo": "compliance-tracker", "severity": "low",
        "title": "Construction module cost fields lack the Money precision/scale convention used elsewhere in the same schema",
        "finding": "The schema enforces numeric(precision:14,scale:2) for currency columns repo-wide, but "
                   "constructionBoqLineItems/constructionLabourRoster/constructionAttendance cost/rate "
                   "fields are bare unconstrained numeric(...) -- no Money value object exists anywhere in "
                   "the codebase, and construction is the most permissive instance of this gap.",
        "artifact_path": "src/lib/db/schema.ts (lines 9272-9294, 9386-9409)",
    },
    {
        "id": "DDD-AI-005", "repo": "veda-advisors", "severity": "info",
        "title": "veda-advisors' only formally-declared entity model (Prisma User/Post) is dead code",
        "finding": "prisma/schema.prisma defines only the default Next.js/Prisma starter template (User, "
                   "Post); a repo-wide grep for prisma. usage and @/lib/db imports returned zero matches -- "
                   "nothing in the application reads or writes through this model. No verifiable "
                   "aggregate/entity modeling exists in this repo.",
        "artifact_path": "prisma/schema.prisma, src/lib/db.ts",
    },
]


@contextlib.contextmanager
def _write_lock():
    os.makedirs(os.path.dirname(_WRITE_LOCK_PATH), exist_ok=True)
    with open(_WRITE_LOCK_PATH, "w") as lockfile:
        fcntl.flock(lockfile, fcntl.LOCK_EX)
        try:
            yield
        finally:
            fcntl.flock(lockfile, fcntl.LOCK_UN)


def _connect():
    conn = sqlite3.connect(DB_PATH, timeout=30)
    conn.execute("PRAGMA journal_mode=WAL")
    conn.row_factory = sqlite3.Row
    return conn


def _now_iso():
    return datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def _finding_id(finding_id):
    raw = f"ai_review:{DOMAIN}:{finding_id}"
    return "fnd_" + hashlib.sha256(raw.encode()).hexdigest()[:24]


def build_records():
    now = _now_iso()
    records = []
    for f in _FINDINGS:
        records.append({
            "finding_id": _finding_id(f["id"]),
            "domain": DOMAIN,
            "standard_cited": STANDARD_CITED,
            "clause_cited": f"ai-review:{f['id']}",
            "artifact_path": f["artifact_path"],
            "finding": f"{f['title']} -- {f['finding']} (full rationale + recommendation: "
                       f"{SOURCE_DOC}, repos.{f['repo']}.ddd_findings[id={f['id']}])",
            "severity": f["severity"],
            "not_covered_by_standard": False,
            "remediation_type": "ai_escalation_required",
            "status": "open",
            "producer": {"kind": "ai_review", "name": "claude-sonnet-5-ddd-semantic-review", "version": REVIEWER_VERSION},
            "repo": f["repo"],
            "_raw": f,
        })
    return records, now


def upsert_findings(conn, records, run_id):
    now = _now_iso()
    new_count = 0
    for r in records:
        prod = r["producer"]
        cur = conn.execute("SELECT status, first_seen_ts FROM audit_findings WHERE finding_id = ?", (r["finding_id"],))
        existing = cur.fetchone()
        if existing is None:
            new_count += 1
            status = r["status"]
            first_seen = now
        else:
            status = existing["status"] if existing["status"] != "open" else r["status"]
            first_seen = existing["first_seen_ts"]
        conn.execute("""
            INSERT INTO audit_findings (
                finding_id, domain, standard_cited, clause_cited,
                artifact_path, artifact_line_start, artifact_line_end, artifact_commit,
                finding, severity, not_covered_by_standard, remediation_type, status,
                producer_kind, producer_name, producer_version, detected_at, repo,
                event_id, owner_decision_ref, raw_json, first_seen_ts, last_seen_ts, run_id
            ) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)
            ON CONFLICT(finding_id) DO UPDATE SET
                finding=excluded.finding, severity=excluded.severity, status=excluded.status,
                detected_at=excluded.detected_at, raw_json=excluded.raw_json,
                last_seen_ts=excluded.last_seen_ts, run_id=excluded.run_id
        """, (
            r["finding_id"], r["domain"], r["standard_cited"], r["clause_cited"],
            r["artifact_path"], None, None, None,
            r["finding"], r["severity"], int(r["not_covered_by_standard"]), r["remediation_type"], status,
            prod["kind"], prod["name"], prod.get("version"), now, r["repo"],
            None, None, json.dumps(r["_raw"], default=str), first_seen, now, run_id,
        ))
    conn.commit()
    return new_count


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--dry-run", action="store_true")
    args = ap.parse_args()

    records, run_id = build_records()
    if args.dry_run:
        print(json.dumps({"would_register": len(records), "ids": [f["id"] for f in _FINDINGS]}, indent=2))
        return 0

    with _write_lock():
        conn = _connect()
        new_count = upsert_findings(conn, records, run_id)
        conn.close()

    print(json.dumps({"ok": True, "total": len(records), "new_findings": new_count}, indent=2))
    return 0


if __name__ == "__main__":
    sys.exit(main())
