#!/usr/bin/env python3
"""VERIDIAN Auditor Engine -- Phase 4, enterprise-architecture AI Review.

Registers the 5 real judgment findings from
ai-os/ENTERPRISE_ARCHITECTURE_DRIFT_REVIEW_2026-07-24.yaml into the same
shared audit_findings table Phase 1-4's deterministic pipelines already
write into -- remediation_type=ai_escalation_required (never
software_fixable: these are judgment calls a lint rule structurally cannot
make, per that document's own per-finding rationale), producer_kind=
ai_review (not oss_tool/custom_script -- distinct producer_kind, matching
this plan's own PART5 distinction between software and AI Review findings).

The finding content itself (id, severity, title, finding text) is NOT
generated by this script -- it is copied verbatim from the drift-review
document, which is the real artifact a human/future Phase 5 pass should
read. This script's only job is to make those 5 real judgment calls queryable
alongside every other domain's findings, idempotently.

Usage:
    python3 register_enterprise_architecture_drift_findings.py [--dry-run]
"""
import argparse
import contextlib
import datetime
import fcntl
import hashlib
import json
import os
import sqlite3
import sys

DB_PATH = os.environ.get("SUPERBOSS_REGISTER_DB", "/opt/veridian/ai-os/memory/superboss-register.sqlite")
_WRITE_LOCK_PATH = DB_PATH + ".writelock"

STANDARD_CITED = "The Open Group TOGAF 10 Standard"
DOMAIN = "enterprise-architecture"
REVIEWER_VERSION = "claude-sonnet-5-2026-07-24"

# Copied verbatim from ai-os/ENTERPRISE_ARCHITECTURE_DRIFT_REVIEW_2026-07-24.yaml
_FINDINGS = [
    {
        "id": "EA-AI-001", "repo": "compliance-tracker", "severity": "medium",
        "title": "Application layer has no internal sub-domain decomposition despite 45+ real capabilities",
        "finding": "src/lib/services/ (50+ files) and src/lib/engines/ (30+ files) are both flat, "
                   "undifferentiated collections with zero subfolders grouping files by named business "
                   "capabilities -- a real TOGAF Application Architecture component-boundary gap the "
                   "dependency-cruiser ddd-bounded-context rule structurally cannot see (no folder boundary "
                   "in src/lib to check against).",
        "artifact_path": "src/lib/services/, src/lib/engines/",
    },
    {
        "id": "EA-AI-002", "repo": "compliance-tracker", "severity": "low",
        "title": "src/app/api/v1/ nests 11 real sub-areas inside ONE 'v1' bounded context",
        "finding": "src/app/api/v1/{brain,compliance,connectors,construction,documents,erp,notices,platform,"
                   "pms,projexa,tasks}/ are treated as one context by the ddd-bounded-context rule "
                   "(documented known simplification) -- 'v1' is really ~11 separate concerns behind an "
                   "API-versioning folder name, not one bounded context.",
        "artifact_path": "src/app/api/v1/",
    },
    {
        "id": "EA-AI-003", "repo": "compliance-tracker", "severity": "info",
        "title": "The 6 live ea-technology-no-import-application findings are a narrow, defensible pattern",
        "finding": "All 6 real findings trace to one file, src/lib/supabase/auth-guard.ts, calling into 6 "
                   "services to make request-time authorization decisions -- judged architecturally "
                   "defensible (auth legitimately needs business context), not a systemic inversion. "
                   "Escalate to medium if the pattern spreads beyond this one file.",
        "artifact_path": "src/lib/supabase/auth-guard.ts",
    },
    {
        "id": "EA-AI-004", "repo": "projexa", "severity": "info",
        "title": "Application layer is genuinely thin -- current flat structure is appropriate, not a gap",
        "finding": "src/lib/services/ has only 3 real files against 30+ route-group capabilities; most "
                   "business logic likely lives directly in route.ts handlers. The 0 dependency-cruiser "
                   "findings reflect genuine current simplicity, not proof the boundaries would hold at "
                   "compliance-tracker's scale.",
        "artifact_path": "src/lib/services/",
    },
    {
        "id": "EA-AI-005", "repo": "veda-advisors", "severity": "info",
        "title": "No architecture to drift from -- appropriately minimal for this repo's real scope",
        "finding": "src/lib contains exactly 2 files (db.ts, utils.ts) against a small real page/API "
                   "surface -- 0 dependency-cruiser findings across all 3 rule sets confirms there is "
                   "nothing to police yet, not a silent skip.",
        "artifact_path": "src/lib/",
    },
]


@contextlib.contextmanager
def _write_lock():
    os.makedirs(os.path.dirname(_WRITE_LOCK_PATH), exist_ok=True)
    with open(_WRITE_LOCK_PATH, "w") as lockfile:
        fcntl.flock(lockfile, fcntl.LOCK_EX)
        try:
            yield
        finally:
            fcntl.flock(lockfile, fcntl.LOCK_UN)


def _connect():
    conn = sqlite3.connect(DB_PATH, timeout=30)
    conn.execute("PRAGMA journal_mode=WAL")
    conn.row_factory = sqlite3.Row
    return conn


def _now_iso():
    return datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def _finding_id(finding_id):
    raw = f"ai_review:{DOMAIN}:{finding_id}"
    return "fnd_" + hashlib.sha256(raw.encode()).hexdigest()[:24]


def build_records():
    now = _now_iso()
    records = []
    for f in _FINDINGS:
        records.append({
            "finding_id": _finding_id(f["id"]),
            "domain": DOMAIN,
            "standard_cited": STANDARD_CITED,
            "clause_cited": f"ai-review:{f['id']}",
            "artifact_path": f["artifact_path"],
            "finding": f"{f['title']} -- {f['finding']} (full rationale + recommendation: "
                       f"ai-os/ENTERPRISE_ARCHITECTURE_DRIFT_REVIEW_2026-07-24.yaml, repos.{f['repo']}."
                       f"drift_findings[id={f['id']}])",
            "severity": f["severity"],
            "not_covered_by_standard": False,
            "remediation_type": "ai_escalation_required",
            "status": "open",
            "producer": {"kind": "ai_review", "name": "claude-sonnet-5-enterprise-architecture-drift-review", "version": REVIEWER_VERSION},
            "repo": f["repo"],
            "_raw": f,
        })
    return records, now


def upsert_findings(conn, records, run_id):
    now = _now_iso()
    new_count = 0
    for r in records:
        prod = r["producer"]
        cur = conn.execute("SELECT status, first_seen_ts FROM audit_findings WHERE finding_id = ?", (r["finding_id"],))
        existing = cur.fetchone()
        if existing is None:
            new_count += 1
            status = r["status"]
            first_seen = now
        else:
            status = existing["status"] if existing["status"] != "open" else r["status"]
            first_seen = existing["first_seen_ts"]
        conn.execute("""
            INSERT INTO audit_findings (
                finding_id, domain, standard_cited, clause_cited,
                artifact_path, artifact_line_start, artifact_line_end, artifact_commit,
                finding, severity, not_covered_by_standard, remediation_type, status,
                producer_kind, producer_name, producer_version, detected_at, repo,
                event_id, owner_decision_ref, raw_json, first_seen_ts, last_seen_ts, run_id
            ) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)
            ON CONFLICT(finding_id) DO UPDATE SET
                finding=excluded.finding, severity=excluded.severity, status=excluded.status,
                detected_at=excluded.detected_at, raw_json=excluded.raw_json,
                last_seen_ts=excluded.last_seen_ts, run_id=excluded.run_id
        """, (
            r["finding_id"], r["domain"], r["standard_cited"], r["clause_cited"],
            r["artifact_path"], None, None, None,
            r["finding"], r["severity"], int(r["not_covered_by_standard"]), r["remediation_type"], status,
            prod["kind"], prod["name"], prod.get("version"), now, r["repo"],
            None, None, json.dumps(r["_raw"], default=str), first_seen, now, run_id,
        ))
    conn.commit()
    return new_count


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--dry-run", action="store_true")
    args = ap.parse_args()

    records, run_id = build_records()
    if args.dry_run:
        print(json.dumps({"would_register": len(records), "ids": [f["id"] for f in _FINDINGS]}, indent=2))
        return 0

    with _write_lock():
        conn = _connect()
        new_count = upsert_findings(conn, records, run_id)
        conn.close()

    print(json.dumps({"ok": True, "total": len(records), "new_findings": new_count}, indent=2))
    return 0


if __name__ == "__main__":
    sys.exit(main())
