#!/usr/bin/env python3
"""VERIDIAN Auditor Engine -- Phase 5, ux domain AI Review.

Registers the 6 real judgment findings from
ai-os/UX_HEURISTIC_REVIEW_2026-07-24.yaml into the same shared
audit_findings table Phase 1-4's deterministic pipelines already write
into -- remediation_type=ai_escalation_required (never software_fixable:
these are Nielsen-heuristic/content-quality judgment calls a WCAG scanner
structurally cannot make, per that document's own per-finding rationale),
producer_kind=ai_review, matching this plan's own PART5 distinction
between software and AI Review findings.

The finding content itself is NOT generated by this script -- it is
copied verbatim from the review document. This script's only job is to
make those 6 real judgment calls queryable alongside every other domain's
findings, idempotently. Same structural pattern as
register_enterprise_architecture_drift_findings.py (Phase 4).

Usage:
    python3 register_ux_heuristic_findings.py [--dry-run]
"""
import argparse
import contextlib
import datetime
import fcntl
import hashlib
import json
import os
import sqlite3
import sys

DB_PATH = os.environ.get("SUPERBOSS_REGISTER_DB", "/opt/veridian/ai-os/memory/superboss-register.sqlite")
_WRITE_LOCK_PATH = DB_PATH + ".writelock"

DOMAIN = "ux"
STANDARD_CITED = ("W3C Web Content Accessibility Guidelines (WCAG) 2.2 Level AA, + Nielsen's 10 Usability "
                   "Heuristics for subjective judgment")
REVIEWER_VERSION = "claude-sonnet-5-2026-07-24"
SOURCE_DOC = "ai-os/UX_HEURISTIC_REVIEW_2026-07-24.yaml"

# Copied verbatim from ai-os/UX_HEURISTIC_REVIEW_2026-07-24.yaml
_FINDINGS = [
    {
        "id": "UX-AI-001", "repo": "compliance-tracker", "severity": "medium",
        "title": "Destructive deletes are one-click in settings sections, with no confirmation",
        "finding": "ChallanSection.tsx, WebhookSection.tsx, and ApiKeySection.tsx wire their trash-icon "
                   "buttons directly to handleDelete(id) with no confirmation dialog, despite the same "
                   "codebase already shipping a shadcn AlertDialog pattern used to confirm AI-agent "
                   "actions in VeriComposer.tsx. Human-initiated permanent deletes of security-sensitive "
                   "records get less protection than agent actions do.",
        "artifact_path": "src/components/ChallanSection.tsx, src/components/WebhookSection.tsx, src/components/ApiKeySection.tsx",
    },
    {
        "id": "UX-AI-002", "repo": "compliance-tracker", "severity": "low",
        "title": "Inconsistent destructive-action pattern: window.confirm() in some pages, nothing in others",
        "finding": "compliance/[id]/page.tsx and veri-meetings/[id]/page.tsx use a raw browser "
                   "window.confirm(), while settings sections use no confirmation at all, and the chat "
                   "composer uses a fully styled AlertDialog -- no single shared convention for "
                   "destructive-action confirmation across the app.",
        "artifact_path": "src/app/(app)/compliance/[id]/page.tsx, src/app/(app)/veri-meetings/[id]/page.tsx",
    },
    {
        "id": "UX-AI-003", "repo": "compliance-tracker", "severity": "low",
        "title": "Generic fallback error text on public-facing lead-gen forms loses the specific server error",
        "finding": "ContactUsForm.tsx and ForgeIntakeComposer.tsx both fall back to an identical generic "
                   "'Something went wrong' string on non-OK responses and network exceptions -- on the "
                   "public /contact, /join-us, and Forge intake forms, exactly where trust matters most.",
        "artifact_path": "src/components/ContactUsForm.tsx, src/components/ForgeIntakeComposer.tsx",
    },
    {
        "id": "UX-AI-004", "repo": "compliance-tracker", "severity": "low",
        "title": "Loading state has no shared convention -- plain text vs. shaped Skeleton placeholders",
        "finding": "training/page.tsx replaces its entire list UI with plain 'Loading...' text, while "
                   "clients/page.tsx renders content-shaped Skeleton blocks. Repo-wide, 51 files use "
                   "Loader2 spinner-only vs 21 using Skeleton, with no apparent rule for which a given "
                   "page gets.",
        "artifact_path": "src/app/(app)/training/page.tsx, src/app/(app)/clients/page.tsx",
    },
    {
        "id": "UX-AI-005", "repo": "projexa", "severity": "medium",
        "title": "Specific server error messages are discarded before reaching the user",
        "finding": "CreateProjectDialog.tsx throws an empty Error() on a non-OK response and always shows "
                   "a generic toast, discarding the specific, meaningful error string the API route "
                   "already computes and returns (err.message via VeridianApiError).",
        "artifact_path": "src/components/CreateProjectDialog.tsx, src/app/api/projects/route.ts",
    },
    {
        "id": "UX-AI-006", "repo": "projexa", "severity": "low",
        "title": "Floor-plan room/furniture deletion is a single click with no confirmation",
        "finding": "FloorPlanEditorClient.tsx's removeRoom/removeSelected fire a DELETE directly from the "
                   "trash-icon onClick with no AlertDialog/confirm() guard -- deleting a populated room is "
                   "irreversible and immediate.",
        "artifact_path": "src/components/FloorPlanEditorClient.tsx",
    },
]


@contextlib.contextmanager
def _write_lock():
    os.makedirs(os.path.dirname(_WRITE_LOCK_PATH), exist_ok=True)
    with open(_WRITE_LOCK_PATH, "w") as lockfile:
        fcntl.flock(lockfile, fcntl.LOCK_EX)
        try:
            yield
        finally:
            fcntl.flock(lockfile, fcntl.LOCK_UN)


def _connect():
    conn = sqlite3.connect(DB_PATH, timeout=30)
    conn.execute("PRAGMA journal_mode=WAL")
    conn.row_factory = sqlite3.Row
    return conn


def _now_iso():
    return datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def _finding_id(finding_id):
    raw = f"ai_review:{DOMAIN}:{finding_id}"
    return "fnd_" + hashlib.sha256(raw.encode()).hexdigest()[:24]


def build_records():
    now = _now_iso()
    records = []
    for f in _FINDINGS:
        records.append({
            "finding_id": _finding_id(f["id"]),
            "domain": DOMAIN,
            "standard_cited": STANDARD_CITED,
            "clause_cited": f"ai-review:{f['id']}",
            "artifact_path": f["artifact_path"],
            "finding": f"{f['title']} -- {f['finding']} (full rationale + recommendation: "
                       f"{SOURCE_DOC}, repos.{f['repo']}.ux_findings[id={f['id']}])",
            "severity": f["severity"],
            "not_covered_by_standard": False,
            "remediation_type": "ai_escalation_required",
            "status": "open",
            "producer": {"kind": "ai_review", "name": "claude-sonnet-5-ux-heuristic-review", "version": REVIEWER_VERSION},
            "repo": f["repo"],
            "_raw": f,
        })
    return records, now


def upsert_findings(conn, records, run_id):
    now = _now_iso()
    new_count = 0
    for r in records:
        prod = r["producer"]
        cur = conn.execute("SELECT status, first_seen_ts FROM audit_findings WHERE finding_id = ?", (r["finding_id"],))
        existing = cur.fetchone()
        if existing is None:
            new_count += 1
            status = r["status"]
            first_seen = now
        else:
            status = existing["status"] if existing["status"] != "open" else r["status"]
            first_seen = existing["first_seen_ts"]
        conn.execute("""
            INSERT INTO audit_findings (
                finding_id, domain, standard_cited, clause_cited,
                artifact_path, artifact_line_start, artifact_line_end, artifact_commit,
                finding, severity, not_covered_by_standard, remediation_type, status,
                producer_kind, producer_name, producer_version, detected_at, repo,
                event_id, owner_decision_ref, raw_json, first_seen_ts, last_seen_ts, run_id
            ) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)
            ON CONFLICT(finding_id) DO UPDATE SET
                finding=excluded.finding, severity=excluded.severity, status=excluded.status,
                detected_at=excluded.detected_at, raw_json=excluded.raw_json,
                last_seen_ts=excluded.last_seen_ts, run_id=excluded.run_id
        """, (
            r["finding_id"], r["domain"], r["standard_cited"], r["clause_cited"],
            r["artifact_path"], None, None, None,
            r["finding"], r["severity"], int(r["not_covered_by_standard"]), r["remediation_type"], status,
            prod["kind"], prod["name"], prod.get("version"), now, r["repo"],
            None, None, json.dumps(r["_raw"], default=str), first_seen, now, run_id,
        ))
    conn.commit()
    return new_count


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--dry-run", action="store_true")
    args = ap.parse_args()

    records, run_id = build_records()
    if args.dry_run:
        print(json.dumps({"would_register": len(records), "ids": [f["id"] for f in _FINDINGS]}, indent=2))
        return 0

    with _write_lock():
        conn = _connect()
        new_count = upsert_findings(conn, records, run_id)
        conn.close()

    print(json.dumps({"ok": True, "total": len(records), "new_findings": new_count}, indent=2))
    return 0


if __name__ == "__main__":
    sys.exit(main())
