#!/usr/bin/env python3
"""VERIDIAN Auditor Engine -- Phase 5, ai-governance domain AI Review.

Registers the 5 real judgment findings from
ai-os/AI_GOVERNANCE_REVIEW_2026-07-24.yaml into the same shared
audit_findings table Phase 1-4's deterministic pipelines already write
into -- remediation_type=ai_escalation_required (never software_fixable:
these are bias/transparency/appropriate-use judgment calls a deterministic
promptfoo test suite structurally cannot make, per that document's own
per-finding rationale), producer_kind=ai_review, matching this plan's own
PART5 distinction between software and AI Review findings.

The finding content itself is NOT generated by this script -- it is
copied verbatim from the review document. This script's only job is to
make those 5 real judgment calls queryable alongside every other domain's
findings, idempotently. Same structural pattern as
register_enterprise_architecture_drift_findings.py (Phase 4).

Usage:
    python3 register_ai_governance_findings.py [--dry-run]
"""
import argparse
import contextlib
import datetime
import fcntl
import hashlib
import json
import os
import sqlite3
import sys

DB_PATH = os.environ.get("SUPERBOSS_REGISTER_DB", "/opt/veridian/ai-os/memory/superboss-register.sqlite")
_WRITE_LOCK_PATH = DB_PATH + ".writelock"

DOMAIN = "ai-governance"
STANDARD_CITED = ("NIST AI Risk Management Framework (AI RMF 1.0) + EU AI Act (Regulation (EU) 2024/1689) "
                   "risk-tiering obligations")
REVIEWER_VERSION = "claude-sonnet-5-2026-07-24"
SOURCE_DOC = "ai-os/AI_GOVERNANCE_REVIEW_2026-07-24.yaml"

# Copied verbatim from ai-os/AI_GOVERNANCE_REVIEW_2026-07-24.yaml
_FINDINGS = [
    {
        "id": "GOV-AI-001", "repo": "compliance-tracker", "severity": "medium",
        "title": "CRM lead/opportunity AI scoring: real people/orgs scored 0-100 by an LLM, with no disclosure to the party being scored",
        "finding": "scoreLead() writes an AI score/reasoning/recommendation directly onto the persistent "
                   "lead record with no approval gate. Internal-facing transparency is good (an "
                   "'Explain AI Decisions' panel exists), but the scored lead/org is never informed it "
                   "was AI-scored, and the input signal (lead.source) is a proxy that can correlate with "
                   "socioeconomic profile with no visible bias review.",
        "artifact_path": "src/lib/services/crm-service.ts (~lines 301-423)",
    },
    {
        "id": "GOV-AI-002", "repo": "compliance-tracker", "severity": "low",
        "title": "GST AI Review prompt explicitly instructs the model to suppress AI self-disclosure",
        "finding": "The gst.ai_review_report system prompt instructs 'no disclaimers about being an AI'. "
                   "A real human-in-the-loop UI pattern exists (discretionary 'AI Review' button), but "
                   "the rendered report text and risk badge carry no AI-provenance marker, which is lost "
                   "if the text is copied into an external workpaper.",
        "artifact_path": "drizzle/0100_gst_reconciliation_engine.sql (~line 340), src/lib/gst/ai-review-report.ts",
    },
    {
        "id": "GOV-AI-003", "repo": "compliance-tracker", "severity": "info",
        "title": "Construction 'risk detection'/'photo progress estimate' AI features are implemented end-to-end but have zero verified UI consumer",
        "finding": "detectBudgetScheduleRisk() and estimateProgressFromPhoto() write AI outputs directly "
                   "to records, but a repo-wide grep in both compliance-tracker and projexa found no "
                   "frontend file reading these outputs back -- no disclosure/human-review UI exists yet "
                   "for these 2 endpoints, unlike the GST/CRM AI surfaces.",
        "artifact_path": "src/app/api/construction/ai/risk-detection/route.ts, src/app/api/construction/ai/estimate-progress/route.ts",
    },
    {
        "id": "GOV-AI-004", "repo": "compliance-tracker", "severity": "low",
        "title": "CRM AI recommendation chains directly into a second, unattended AI planning call within one synchronous user click",
        "finding": "createChainedTask() inserts a follow-up task and immediately awaits a second, "
                   "independent LLM planning call (executeTask) in the same request -- the human only "
                   "approved creating a follow-up task, not the content of the second AI's plan.",
        "artifact_path": "src/lib/services/crm-service.ts (lines 425-460)",
    },
    {
        "id": "GOV-AI-005", "repo": "veda-advisors", "severity": "info",
        "title": "veda-advisors confirmed to have no AI/LLM integration",
        "finding": "Repo-wide grep for anthropic|openai|claude-|generateText|chat.completions|llm|gpt- "
                   "found only doc-file/image-filename matches -- no source file calls an LLM API.",
        "artifact_path": "repo-wide grep, /opt/veridian/repos/veda-advisors",
    },
]


@contextlib.contextmanager
def _write_lock():
    os.makedirs(os.path.dirname(_WRITE_LOCK_PATH), exist_ok=True)
    with open(_WRITE_LOCK_PATH, "w") as lockfile:
        fcntl.flock(lockfile, fcntl.LOCK_EX)
        try:
            yield
        finally:
            fcntl.flock(lockfile, fcntl.LOCK_UN)


def _connect():
    conn = sqlite3.connect(DB_PATH, timeout=30)
    conn.execute("PRAGMA journal_mode=WAL")
    conn.row_factory = sqlite3.Row
    return conn


def _now_iso():
    return datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def _finding_id(finding_id):
    raw = f"ai_review:{DOMAIN}:{finding_id}"
    return "fnd_" + hashlib.sha256(raw.encode()).hexdigest()[:24]


def build_records():
    now = _now_iso()
    records = []
    for f in _FINDINGS:
        records.append({
            "finding_id": _finding_id(f["id"]),
            "domain": DOMAIN,
            "standard_cited": STANDARD_CITED,
            "clause_cited": f"ai-review:{f['id']}",
            "artifact_path": f["artifact_path"],
            "finding": f"{f['title']} -- {f['finding']} (full rationale + recommendation: "
                       f"{SOURCE_DOC}, repos.{f['repo']}.ai_governance_findings[id={f['id']}])",
            "severity": f["severity"],
            "not_covered_by_standard": False,
            "remediation_type": "ai_escalation_required",
            "status": "open",
            "producer": {"kind": "ai_review", "name": "claude-sonnet-5-ai-governance-review", "version": REVIEWER_VERSION},
            "repo": f["repo"],
            "_raw": f,
        })
    return records, now


def upsert_findings(conn, records, run_id):
    now = _now_iso()
    new_count = 0
    for r in records:
        prod = r["producer"]
        cur = conn.execute("SELECT status, first_seen_ts FROM audit_findings WHERE finding_id = ?", (r["finding_id"],))
        existing = cur.fetchone()
        if existing is None:
            new_count += 1
            status = r["status"]
            first_seen = now
        else:
            status = existing["status"] if existing["status"] != "open" else r["status"]
            first_seen = existing["first_seen_ts"]
        conn.execute("""
            INSERT INTO audit_findings (
                finding_id, domain, standard_cited, clause_cited,
                artifact_path, artifact_line_start, artifact_line_end, artifact_commit,
                finding, severity, not_covered_by_standard, remediation_type, status,
                producer_kind, producer_name, producer_version, detected_at, repo,
                event_id, owner_decision_ref, raw_json, first_seen_ts, last_seen_ts, run_id
            ) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)
            ON CONFLICT(finding_id) DO UPDATE SET
                finding=excluded.finding, severity=excluded.severity, status=excluded.status,
                detected_at=excluded.detected_at, raw_json=excluded.raw_json,
                last_seen_ts=excluded.last_seen_ts, run_id=excluded.run_id
        """, (
            r["finding_id"], r["domain"], r["standard_cited"], r["clause_cited"],
            r["artifact_path"], None, None, None,
            r["finding"], r["severity"], int(r["not_covered_by_standard"]), r["remediation_type"], status,
            prod["kind"], prod["name"], prod.get("version"), now, r["repo"],
            None, None, json.dumps(r["_raw"], default=str), first_seen, now, run_id,
        ))
    conn.commit()
    return new_count


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--dry-run", action="store_true")
    args = ap.parse_args()

    records, run_id = build_records()
    if args.dry_run:
        print(json.dumps({"would_register": len(records), "ids": [f["id"] for f in _FINDINGS]}, indent=2))
        return 0

    with _write_lock():
        conn = _connect()
        new_count = upsert_findings(conn, records, run_id)
        conn.close()

    print(json.dumps({"ok": True, "total": len(records), "new_findings": new_count}, indent=2))
    return 0


if __name__ == "__main__":
    sys.exit(main())
