#!/usr/bin/env python3
"""VERIDIAN Auditor Engine -- Phase 5, workflow domain AI Review.

Registers the 4 real judgment findings from
ai-os/WORKFLOW_LOGIC_REVIEW_2026-07-24.yaml into the same shared
audit_findings table Phase 1-4's deterministic pipelines already write
into -- remediation_type=ai_escalation_required (never software_fixable:
these are business-logic-correctness judgment calls a transition-legality
validator structurally cannot make, per that document's own per-finding
rationale), producer_kind=ai_review, matching this plan's own PART5
distinction between software and AI Review findings.

The finding content itself is NOT generated by this script -- it is
copied verbatim from the review document. This script's only job is to
make those 4 real judgment calls queryable alongside every other domain's
findings, idempotently. Same structural pattern as
register_enterprise_architecture_drift_findings.py (Phase 4).

Usage:
    python3 register_workflow_logic_findings.py [--dry-run]
"""
import argparse
import contextlib
import datetime
import fcntl
import hashlib
import json
import os
import sqlite3
import sys

DB_PATH = os.environ.get("SUPERBOSS_REGISTER_DB", "/opt/veridian/ai-os/memory/superboss-register.sqlite")
_WRITE_LOCK_PATH = DB_PATH + ".writelock"

DOMAIN = "workflow"
STANDARD_CITED = "OMG BPMN 2.0 (Business Process Model and Notation)"
REVIEWER_VERSION = "claude-sonnet-5-2026-07-24"
SOURCE_DOC = "ai-os/WORKFLOW_LOGIC_REVIEW_2026-07-24.yaml"

# Copied verbatim from ai-os/WORKFLOW_LOGIC_REVIEW_2026-07-24.yaml
_FINDINGS = [
    {
        "id": "WF-AI-001", "repo": "compliance-tracker", "severity": "medium",
        "title": "Lost-update race condition in multi-approver quorum counting",
        "finding": "decideApprovalStep reads then writes the approvalsReceived counter in application "
                   "code with no row lock and no unique constraint on the approvals table -- two "
                   "qualifying approvers deciding concurrently on a four-eyes-mandated 2-of-2 step can "
                   "both compute the same newCount, silently stalling quorum despite both approval rows "
                   "being correctly inserted.",
        "artifact_path": "src/lib/services/approval-workflow-service.ts (decideApprovalStep, lines 320-378)",
    },
    {
        "id": "WF-AI-002", "repo": "compliance-tracker", "severity": "medium",
        "title": "Reverse-auction bid/leader update is not atomic, contradicting its own code comment",
        "finding": "submitAuctionBid's own header comment claims the bid insert and auction "
                   "leader/lowest-bid update are atomic, but the implementation does 3 separate "
                   "un-transacted round trips with no row lock -- concurrent bids can both pass a "
                   "stale undercut check and leave a higher bid recorded as the 'current lowest'.",
        "artifact_path": "src/lib/services/erp-procurement-workflow-service.ts (submitAuctionBid, lines 356-360, 429-452)",
    },
    {
        "id": "WF-AI-003", "repo": "compliance-tracker", "severity": "low",
        "title": "Construction field workflow status transitions write no audit log, inconsistent with sibling approval workflows",
        "finding": "None of the 5 status-transition functions in construction-field-workflow-service.ts "
                   "call logActivity, unlike essentially every status change in "
                   "approval-workflow-service.ts and erp-procurement-workflow-service.ts -- "
                   "verifyPunchListItemClosed enforces a real self-approval guard but leaves no audit "
                   "trail of who verified closure and when.",
        "artifact_path": "src/lib/services/construction-field-workflow-service.ts (lines 46-169)",
    },
    {
        "id": "WF-AI-004", "repo": "projexa", "severity": "low",
        "title": "Punch-list status transitions fire no notification, unlike creation and submittal review",
        "finding": "PATCH /api/punch-list/[id] (the 'ready for review'/'verified closed' transitions) "
                   "only proxies to callVeridian and never calls notifyOrgMembers, unlike punch-list "
                   "creation and the sibling submittal-review PATCH handler, which both notify org "
                   "members on their respective transitions.",
        "artifact_path": "src/app/api/punch-list/[id]/route.ts",
    },
]


@contextlib.contextmanager
def _write_lock():
    os.makedirs(os.path.dirname(_WRITE_LOCK_PATH), exist_ok=True)
    with open(_WRITE_LOCK_PATH, "w") as lockfile:
        fcntl.flock(lockfile, fcntl.LOCK_EX)
        try:
            yield
        finally:
            fcntl.flock(lockfile, fcntl.LOCK_UN)


def _connect():
    conn = sqlite3.connect(DB_PATH, timeout=30)
    conn.execute("PRAGMA journal_mode=WAL")
    conn.row_factory = sqlite3.Row
    return conn


def _now_iso():
    return datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def _finding_id(finding_id):
    raw = f"ai_review:{DOMAIN}:{finding_id}"
    return "fnd_" + hashlib.sha256(raw.encode()).hexdigest()[:24]


def build_records():
    now = _now_iso()
    records = []
    for f in _FINDINGS:
        records.append({
            "finding_id": _finding_id(f["id"]),
            "domain": DOMAIN,
            "standard_cited": STANDARD_CITED,
            "clause_cited": f"ai-review:{f['id']}",
            "artifact_path": f["artifact_path"],
            "finding": f"{f['title']} -- {f['finding']} (full rationale + recommendation: "
                       f"{SOURCE_DOC}, repos.{f['repo']}.workflow_findings[id={f['id']}])",
            "severity": f["severity"],
            "not_covered_by_standard": False,
            "remediation_type": "ai_escalation_required",
            "status": "open",
            "producer": {"kind": "ai_review", "name": "claude-sonnet-5-workflow-logic-review", "version": REVIEWER_VERSION},
            "repo": f["repo"],
            "_raw": f,
        })
    return records, now


def upsert_findings(conn, records, run_id):
    now = _now_iso()
    new_count = 0
    for r in records:
        prod = r["producer"]
        cur = conn.execute("SELECT status, first_seen_ts FROM audit_findings WHERE finding_id = ?", (r["finding_id"],))
        existing = cur.fetchone()
        if existing is None:
            new_count += 1
            status = r["status"]
            first_seen = now
        else:
            status = existing["status"] if existing["status"] != "open" else r["status"]
            first_seen = existing["first_seen_ts"]
        conn.execute("""
            INSERT INTO audit_findings (
                finding_id, domain, standard_cited, clause_cited,
                artifact_path, artifact_line_start, artifact_line_end, artifact_commit,
                finding, severity, not_covered_by_standard, remediation_type, status,
                producer_kind, producer_name, producer_version, detected_at, repo,
                event_id, owner_decision_ref, raw_json, first_seen_ts, last_seen_ts, run_id
            ) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)
            ON CONFLICT(finding_id) DO UPDATE SET
                finding=excluded.finding, severity=excluded.severity, status=excluded.status,
                detected_at=excluded.detected_at, raw_json=excluded.raw_json,
                last_seen_ts=excluded.last_seen_ts, run_id=excluded.run_id
        """, (
            r["finding_id"], r["domain"], r["standard_cited"], r["clause_cited"],
            r["artifact_path"], None, None, None,
            r["finding"], r["severity"], int(r["not_covered_by_standard"]), r["remediation_type"], status,
            prod["kind"], prod["name"], prod.get("version"), now, r["repo"],
            None, None, json.dumps(r["_raw"], default=str), first_seen, now, run_id,
        ))
    conn.commit()
    return new_count


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--dry-run", action="store_true")
    args = ap.parse_args()

    records, run_id = build_records()
    if args.dry_run:
        print(json.dumps({"would_register": len(records), "ids": [f["id"] for f in _FINDINGS]}, indent=2))
        return 0

    with _write_lock():
        conn = _connect()
        new_count = upsert_findings(conn, records, run_id)
        conn.close()

    print(json.dumps({"ok": True, "total": len(records), "new_findings": new_count}, indent=2))
    return 0


if __name__ == "__main__":
    sys.exit(main())
