// AUTO-GENERATED by ai-os-scripts/generate_route_tests.py -- Phase 1 route
// test auto-generation, route_id=RT-trend_analysis_engine-001, capability_name=trend_analysis_engine.
// Real call target derived by grepping task-execution-engine.ts's live
// dispatchEngine() switch; call_args/assertions are the one curated fixture
// (REGISTERED_FIXTURES) for this capability, computed against the engine's
// own documented formula. Do not hand-edit -- regenerate via the script.
import { describe, expect, test } from "bun:test"
import { analyzeTrendExplained } from "@/lib/engines/analytics-engine"

describe("route test: RT-trend_analysis_engine-001 (trend_analysis_engine)", () => {
  test("real dispatch target analyzeTrendExplained() executes and matches the documented formula", () => {
    const result = analyzeTrendExplained([1, 2, 3, 4, 5])
    expect(result.value.direction).toBe("increasing")
  expect(result.explanation).toContain("upward")
  })
})
