// AUTO-GENERATED by ai-os-scripts/generate_route_tests.py -- Phase 1 route
// test auto-generation, route_id=RT-gratuity_calculator-001, capability_name=gratuity_calculator.
// Real call target derived by grepping task-execution-engine.ts's live
// dispatchEngine() switch; call_args/assertions are the one curated fixture
// (REGISTERED_FIXTURES) for this capability, computed against the engine's
// own documented formula. Do not hand-edit -- regenerate via the script.
import { describe, expect, test } from "bun:test"
import { calculateGratuity } from "@/lib/engines/payroll-engine"

describe("route test: RT-gratuity_calculator-001 (gratuity_calculator)", () => {
  test("real dispatch target calculateGratuity() executes and matches the documented formula", () => {
    const result = calculateGratuity({ lastDrawnMonthlySalary: 50000, yearsOfService: 10, isCoveredUnderAct: true })
    expect(result.gratuityAmount).toBe(288461.54)
  expect(result.roundedYearsOfService).toBe(10)
  expect(result.statutoryCapApplied).toBe(false)
  })
})
