// AUTO-GENERATED by ai-os-scripts/generate_route_replays.py -- Phase 3 route
// replay capture/replay, route_id=RT-commission_calculator-001, capability_name=commission_calculator.
// Real call target + call_args reused verbatim from Phase 1's
// generate_route_tests.py REGISTERED_FIXTURES. Do not hand-edit --
// regenerate via the script.
import { calculatePayrollCommission } from "@/lib/engines/payroll-engine"

const result = calculatePayrollCommission(100000, 5)
console.log(JSON.stringify(result))
