// AUTO-GENERATED by ai-os-scripts/generate_route_tests.py -- Phase 1 route
// test auto-generation, route_id=RT-commission_calculator-001, capability_name=commission_calculator.
// Real call target derived by grepping task-execution-engine.ts's live
// dispatchEngine() switch; call_args/assertions are the one curated fixture
// (REGISTERED_FIXTURES) for this capability, computed against the engine's
// own documented formula. Do not hand-edit -- regenerate via the script.
import { describe, expect, test } from "bun:test"
import { calculatePayrollCommission } from "@/lib/engines/payroll-engine"

describe("route test: RT-commission_calculator-001 (commission_calculator)", () => {
  test("real dispatch target calculatePayrollCommission() executes and matches the documented formula", () => {
    const result = calculatePayrollCommission(100000, 5)
    expect(result).toBe(5000)
  })
})
