// AUTO-GENERATED by ai-os-scripts/generate_route_tests.py -- Phase 1 route
// test auto-generation, route_id=RT-gst_calculation_engine-001, capability_name=gst_calculation_engine.
// Real call target derived by grepping task-execution-engine.ts's live
// dispatchEngine() switch; call_args/assertions are the one curated fixture
// (REGISTERED_FIXTURES) for this capability, computed against the engine's
// own documented formula. Do not hand-edit -- regenerate via the script.
import { describe, expect, test } from "bun:test"
import { calculateGst } from "@/lib/engines/in/gst-engine"

describe("route test: RT-gst_calculation_engine-001 (gst_calculation_engine)", () => {
  test("real dispatch target calculateGst() executes and matches the documented formula", () => {
    const result = calculateGst({ taxableAmount: 10000, gstRatePercent: 18, supplierStateCode: "27", buyerStateCode: "29" })
    expect(result.isInterState).toBe(true)
  expect(result.igst).toBe(1800)
  expect(result.cgst).toBe(0)
  expect(result.sgst).toBe(0)
  expect(result.totalAmount).toBe(11800)
  })
})
