// AUTO-GENERATED by ai-os-scripts/generate_route_replays.py -- Phase 3 route
// replay capture/replay, route_id=RT-gratuity_calculator-001, capability_name=gratuity_calculator.
// Real call target + call_args reused verbatim from Phase 1's
// generate_route_tests.py REGISTERED_FIXTURES. Do not hand-edit --
// regenerate via the script.
import { calculateGratuity } from "@/lib/engines/payroll-engine"

const result = calculateGratuity({ lastDrawnMonthlySalary: 50000, yearsOfService: 10, isCoveredUnderAct: true })
console.log(JSON.stringify(result))
