// AUTO-GENERATED by ai-os-scripts/generate_route_replays.py -- Phase 3 route
// replay capture/replay, route_id=RT-trend_analysis_engine-001, capability_name=trend_analysis_engine.
// Real call target + call_args reused verbatim from Phase 1's
// generate_route_tests.py REGISTERED_FIXTURES. Do not hand-edit --
// regenerate via the script.
import { analyzeTrendExplained } from "@/lib/engines/analytics-engine"

const result = analyzeTrendExplained([1, 2, 3, 4, 5])
console.log(JSON.stringify(result))
